name: CI (型チェックとテスト)

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node 16で型チェックとテスト
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          # Netlifyは.nvmrcを検出するため、そちらが変われば適宜変えること
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: 型チェック
        run: yarn run typecheck
      - name: テスト
        run: yarn run test
