name: CI (型チェックとテスト)

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node 18で型チェックとテスト
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          # Netlifyは.nvmrcを検出するため、そちらが変われば適宜変えること
          node-version: 18

      # pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
          run_install: false

      # pnpmとキャッシュの併用
      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: pnpmのストアのパスを取得
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: pnpmのキャッシュ
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 依存のインストール
        run: pnpm install

      - name: 型チェック
        run: pnpm run typecheck

      - name: テスト
        run: pnpm run test
